/**
 * One-shot cleanup: collapse Website-Analysis to one row per unique website.
 *
 * Background:
 *   Until v1.8.9 the dedup worker relied on the unique index on
 *   `Website-Analysis.website` to reject duplicates at insert time.
 *   The index silently failed to be created in prod (autoIndex did not
 *   have the privilege), so every job run re-inserted every source row.
 *   Result: ~10M docs in Website-Analysis vs ~6M unique source URLs.
 *
 * Strategy:
 *   For each duplicate group (same `website`), keep the one with the
 *   smallest `_id` (oldest insertion) and delete the rest. Streams
 *   group-by-group so memory stays bounded even on 10M docs.
 *
 * Safety:
 *   - DOES delete duplicate rows from Website-Analysis. The Scraped-Data
 *     source rows are untouched — Website-Analysis is purely derived
 *     and can be regenerated by re-running the analysis job anyway.
 *   - Prints a summary every 100 groups so you can watch progress.
 *   - Idempotent: re-running after success is a no-op.
 *
 * After the script finishes, the createIndex call at the end will succeed
 * (no duplicates left) and lock the collection against future regressions.
 *
 * Run: npm run dedup:website-analysis
 */

require('../config/loadEnv');

const mongoose = require('mongoose');

const BATCH_LOG_EVERY = 100; // log progress every N groups
const DELETE_BATCH = 500;    // chunk size for deleteMany

async function run() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error('MONGODB_URI is not set. Check .env / APP_STATE.');
    process.exit(1);
  }

  await mongoose.connect(uri, { serverSelectionTimeoutMS: 30_000 });
  console.log(`Connected: ${mongoose.connection.host}/${mongoose.connection.name}`);

  const col = mongoose.connection.collection('Website-Analysis');

  // ── Quick reality check ─────────────────────────────────────────────────────
  const before = await col.estimatedDocumentCount();
  console.log(`Website-Analysis docs before: ${before.toLocaleString()}`);

  // ── Find all duplicate groups (website -> [ids in oldest-first order]) ──────
  console.log('\nScanning for duplicate websites (aggregate, allowDiskUse)...');
  const tStart = Date.now();

  // We aggregate keep:min(_id), idsToDelete:array(_id) excluding the keeper.
  // Streaming via cursor so a 10M-doc collection doesn't materialize in memory.
  const cursor = col.aggregate([
    { $match: { website: { $nin: [null, ''] } } },
    { $sort: { _id: 1 } },
    {
      $group: {
        _id: '$website',
        keepId: { $first: '$_id' },
        allIds: { $push: '$_id' },
        count:  { $sum: 1 },
      },
    },
    { $match: { count: { $gte: 2 } } },
  ], { allowDiskUse: true, batchSize: 200 });

  let groupCount = 0;
  let totalToDelete = 0;
  let totalDeleted = 0;
  let buffer = [];

  const flushDeletes = async () => {
    if (buffer.length === 0) return;
    const chunk = buffer;
    buffer = [];
    const result = await col.deleteMany({ _id: { $in: chunk } });
    totalDeleted += result.deletedCount;
  };

  for await (const g of cursor) {
    groupCount++;
    // Skip the oldest (keepId), queue the rest for deletion.
    for (const id of g.allIds) {
      if (String(id) === String(g.keepId)) continue;
      buffer.push(id);
      totalToDelete++;
      if (buffer.length >= DELETE_BATCH) await flushDeletes();
    }
    if (groupCount % BATCH_LOG_EVERY === 0) {
      console.log(`  groups=${groupCount.toLocaleString()}  toDelete=${totalToDelete.toLocaleString()}  deleted=${totalDeleted.toLocaleString()}  elapsed=${Math.round((Date.now()-tStart)/1000)}s`);
    }
  }
  await flushDeletes();

  console.log(`\nDuplicate scan complete:`);
  console.log(`  duplicate-website groups : ${groupCount.toLocaleString()}`);
  console.log(`  rows queued for deletion : ${totalToDelete.toLocaleString()}`);
  console.log(`  rows deleted             : ${totalDeleted.toLocaleString()}`);
  console.log(`  elapsed                  : ${Math.round((Date.now()-tStart)/1000)}s`);

  const after = await col.estimatedDocumentCount();
  console.log(`\nWebsite-Analysis docs after: ${after.toLocaleString()} (was ${before.toLocaleString()})`);

  // ── Lock in the unique index so the bug can't recur ────────────────────────
  console.log('\nCreating unique index on `website` to prevent future duplicates...');
  try {
    await col.createIndex({ website: 1 }, { unique: true, name: 'website_unique_idx' });
    console.log('  ✓ unique index created (or already existed).');
  } catch (err) {
    if (err.code === 11000 || /duplicate/i.test(err.message || '')) {
      console.error('  ✗ unique index NOT created — duplicates remain. Re-run this script.');
    } else if (err.codeName === 'Unauthorized' || /not authorized/i.test(err.message || '')) {
      console.error('  ✗ unique index NOT created — Mongo user lacks createIndex privilege.');
      console.error('    Grant the role or have a dbAdmin user run:');
      console.error("    db['Website-Analysis'].createIndex({ website: 1 }, { unique: true, name: 'website_unique_idx' })");
    } else {
      console.error(`  ✗ unique index NOT created: ${err.message}`);
    }
  }

  await mongoose.disconnect();
  console.log('\nDone.');
}

run().catch((err) => {
  console.error('\ndedup FAILED:', err);
  process.exit(1);
});
